# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('home_team', models.IntegerField(blank=True, null=True)),
                ('away_team', models.IntegerField(blank=True, null=True)),
                ('played', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'school',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('home_team', models.IntegerField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_team', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('home_notes', models.TextField(blank=True, null=True)),
                ('away_notes', models.TextField(blank=True, null=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teamsports.Schedule')),
            ],
            options={
                'db_table': 'score',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('sport_id', models.AutoField(primary_key=True, serialize=False)),
                ('sport_name', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'sports',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, max_length=225, null=True)),
                ('division', models.CharField(blank=True, max_length=225, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teamsports.School')),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teamsports.Sports')),
            ],
            options={
                'db_table': 'teams',
                'managed': True,
            },
        ),
    ]
