# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_id',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='sports',
            old_name='sport_id',
            new_name='sport',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='sport',
            new_name='sport_id',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='team_id',
            new_name='team',
        ),
    ]
