# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0002_auto_20161113_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='home_team',
        ),
        migrations.AddField(
            model_name='schedule',
            name='away',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_set', to='teamsports.Teams'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_set', to='teamsports.Teams'),
        ),
    ]
