# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0003_auto_20161114_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='away_notes',
        ),
        migrations.RemoveField(
            model_name='score',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='score',
            name='home_notes',
        ),
        migrations.RemoveField(
            model_name='score',
            name='home_team',
        ),
    ]
