# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0006_auto_20161120_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
