# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0007_auto_20161120_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='loss',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='tie',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='win',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
