# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0009_auto_20170104_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={},
        ),
    ]
