# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0010_auto_20170104_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='away_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='home_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
