# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0013_photo_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='uploaded_at',
            new_name='uploaded_date',
        ),
    ]
