# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0014_auto_20170107_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='uploaded_date',
            new_name='upload_date',
        ),
    ]
