# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 18:04
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0015_auto_20170107_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='gamepics/'),
        ),
    ]
