# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamsports', '0019_auto_20170114_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamenotes',
            old_name='away_notes',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='gamenotes',
            name='home_notes',
        ),
        migrations.RemoveField(
            model_name='gamenotes',
            name='other_notes',
        ),
        migrations.AddField(
            model_name='gamenotes',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
