# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0020_auto_20170114_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenotes',
            name='reported_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
