# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0021_gamenotes_reported_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamenotes',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsports.Schedule'),
        ),
    ]
