# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 13:56
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0022_auto_20170114_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='sports',
            name='pic',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='sportpics/'),
        ),
    ]
