# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 20:21
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0025_auto_20170122_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='pic',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='/teampics/emptyfield.jpg', upload_to='teampics/'),
        ),
    ]
