# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0030_auto_20170217_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsports.Sports'),
        ),
    ]
