# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 14:27
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0031_profile_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(upload_to='gamepics/'),
        ),
    ]
