# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 14:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0032_auto_20170307_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
