# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 10:25
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0034_auto_20170324_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='json',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
