# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-20 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0038_auto_20170513_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=225, null=True)),
                ('last_name', models.CharField(blank=True, max_length=225, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamsports.School')),
                ('spring_2017_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamsports.Teams')),
            ],
        ),
    ]
