# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-21 18:12
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teamsports', '0041_player_is_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pic',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='player/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
